/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SkolestudioImport } from './routes/skolestudio'
import { Route as RedapticImport } from './routes/redaptic'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const SkolestudioRoute = SkolestudioImport.update({
  id: '/skolestudio',
  path: '/skolestudio',
  getParentRoute: () => rootRoute,
} as any)

const RedapticRoute = RedapticImport.update({
  id: '/redaptic',
  path: '/redaptic',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/redaptic': {
      id: '/redaptic'
      path: '/redaptic'
      fullPath: '/redaptic'
      preLoaderRoute: typeof RedapticImport
      parentRoute: typeof rootRoute
    }
    '/skolestudio': {
      id: '/skolestudio'
      path: '/skolestudio'
      fullPath: '/skolestudio'
      preLoaderRoute: typeof SkolestudioImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/redaptic': typeof RedapticRoute
  '/skolestudio': typeof SkolestudioRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/redaptic': typeof RedapticRoute
  '/skolestudio': typeof SkolestudioRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/redaptic': typeof RedapticRoute
  '/skolestudio': typeof SkolestudioRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/redaptic' | '/skolestudio'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/redaptic' | '/skolestudio'
  id: '__root__' | '/' | '/redaptic' | '/skolestudio'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RedapticRoute: typeof RedapticRoute
  SkolestudioRoute: typeof SkolestudioRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RedapticRoute: RedapticRoute,
  SkolestudioRoute: SkolestudioRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/redaptic",
        "/skolestudio"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/redaptic": {
      "filePath": "redaptic.tsx"
    },
    "/skolestudio": {
      "filePath": "skolestudio.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
